Revert "kenzo: Enable USB debugging at boot"
* Fixup duplicate sysprop assignment

error: found duplicate sysprop assignments:
ro.adb.secure=0
ro.adb.secure=1
error: found duplicate sysprop assignments:
ro.secure=0
ro.secure=1

This reverts commit dc17f07968a6a8397ece3fa2891a1c1eb54e8c6c.

Signed-off-by: dodyirawan85 <40514988+dodyirawan85@users.noreply.github.com>